import { CreativesReview } from "@/components/CreativesReview";
import { CAST } from "@/lib/visual/cast";
import { SHAPES } from "@/lib/visual/shapes";

export const metadata = {
  title: "Creatives review - Welltread Vault",
  robots: { index: false, follow: false, nocache: true },
};

export type Creative = {
  id: string;
  src: string;
  title: string;
  intent: string;
  prompt: string;
  aspect: "1:1" | "4:5" | "16:9" | "9:16" | "3:2" | "2:3";
  source: "nano-banana" | "depositphotos";
};

const SAMPLES: Creative[] = [
  {
    id: "sample_01_woman_55_stretch",
    src: "/samples/welltread_sample_01_woman_55_stretch.png",
    title: "Editorial portrait - 55, stretch",
    intent: "First-pass LP hero candidate. One-off (not in cast yet).",
    prompt:
      "55yo woman, silver-grey hair, mid-stretch in a sun-lit minimalist home. Sage tank top, paper-warm wall, Kinfolk/Gentlewoman aesthetic.",
    aspect: "4:5",
    source: "nano-banana",
  },
  {
    id: "sample_02_man_70_balance",
    src: "/samples/welltread_sample_02_man_70_balance.png",
    title: "Editorial portrait - 70, balance hold",
    intent: "First-pass senior LP hero candidate. One-off (not in cast yet).",
    prompt:
      "70yo man, full grey hair, one-leg balance hold by a wooden chair. Sage henley, NYT Well section feel.",
    aspect: "4:5",
    source: "nano-banana",
  },
  {
    id: "sample_03_exercise_lineart",
    src: "/samples/welltread_sample_03_exercise_lineart.png",
    title: "Exercise line illustration - seated cat-cow",
    intent: "Exercise instruction visual primitive. Tests the line-art language.",
    prompt:
      "Single-weight sage line illustration on paper, seated cat-cow stretch. Mid-century editorial style.",
    aspect: "1:1",
    source: "nano-banana",
  },
  {
    id: "sample_04_backdrop",
    src: "/samples/welltread_sample_04_backdrop.png",
    title: "Abstract backdrop",
    intent:
      "Section backgrounds, stat cards, cinematic loader. Tests the palette as pure mood.",
    prompt: "Soft sage / paper-cream / clay gradient with paper grain texture.",
    aspect: "16:9",
    source: "nano-banana",
  },
];

const GROUP_HEROES: Creative[] = [
  {
    id: "cast_group_hero",
    src: "/cast/group_hero.png",
    title: "Group hero - standing portrait",
    intent:
      "Consistency check: all four cast members in a single frame. If their faces hold across this, they'll hold across single-character scenes. Tests for visual identity drift in multi-subject prompts.",
    prompt:
      "Group portrait, left to right: Maria, David, James, Eleanor. Each character described with full distinctive-feature paragraph. Sage / paper-cream palette. NYT Well section group feature. 16:9.",
    aspect: "16:9",
    source: "nano-banana",
  },
  {
    id: "cast_group_mat_catcow",
    src: "/cast/group_mat_catcow.png",
    title: "Group on mats - seated cat-cow",
    intent:
      "All 4 cast members performing the same mobility drill on individual yoga mats. Tests in-pose group consistency + class-feel for plan reveal hero.",
    prompt:
      "All 4 characters seated cross-legged on individual yoga mats, performing seated cat-cow stretch. Same studio, same light, same palette.",
    aspect: "16:9",
    source: "nano-banana",
  },
  {
    id: "cast_group_balance_chairs",
    src: "/cast/group_balance_with_chairs.png",
    title: "Group balance - regression vs progression",
    intent:
      "Same exercise (single-leg balance), differentiated by support level. Maria + David freestanding (advanced); James + Eleanor with chair support (regressed). Demonstrates the contraindication-aware progression visually - one of the most important brand-story shots.",
    prompt:
      "All 4 characters performing single-leg balance hold. Eleanor and James with fingertips on dining-chair backs; Maria and David freestanding. 16:9.",
    aspect: "16:9",
    source: "nano-banana",
  },
];

const CAST_CREATIVES: Creative[] = Object.values(CAST).map((c) => ({
  id: `cast_${c.id}`,
  src: c.canonicalImage,
  title: `${c.name}, ${c.age} - ${c.tagline}`,
  intent: `Canonical reference for ${c.name}. Reused across LPs, quiz interstitials, plan reveal, and ad creative. Future generations cite this image + ${c.name}'s description for consistency.`,
  prompt: c.description,
  aspect: "4:5",
  source: "nano-banana",
}));

const MARIA_SCENES: Creative[] = [
  {
    id: "scene_maria_cat_cow",
    src: "/scenes/maria_cat_cow.png",
    title: "Maria - seated cat-cow",
    intent:
      "Tests whether Maria's identity holds in an active pose. Generated by prepending Maria's stable description to a scene-specific prompt.",
    prompt: `${CAST.maria.description} Performing a seated cat-cow spinal stretch on a yoga mat, gently rounding her upper back, hands on knees, eyes closed.`,
    aspect: "4:5",
    source: "nano-banana",
  },
  {
    id: "scene_maria_side_stretch",
    src: "/scenes/maria_side_stretch.png",
    title: "Maria - standing side stretch",
    intent:
      "Tests Maria's identity in a standing pose with elongated body line.",
    prompt: `${CAST.maria.description} Standing barefoot, both arms reaching up and over to one side, lateral bend at the waist, eyes lightly closed.`,
    aspect: "4:5",
    source: "nano-banana",
  },
  {
    id: "scene_maria_chair_balance",
    src: "/scenes/maria_chair_balance.png",
    title: "Maria - chair-supported single-leg balance",
    intent:
      "Tests Maria in a balance pose with prop. Same character, new movement archetype.",
    prompt: `${CAST.maria.description} Performing a single-leg balance hold, fingertips on the back of a wooden dining chair, one foot lifted slightly off the ground.`,
    aspect: "4:5",
    source: "nano-banana",
  },
];

const SHAPE_CREATIVES: Creative[] = Object.values(SHAPES).map((s) => ({
  id: `shape_${s.id}`,
  src: s.image,
  title: `${s.name} - drill archetype`,
  intent: `${s.meaning} Used for: ${s.uses.join("; ")}.`,
  prompt: "See drill-shape vocabulary in src/lib/visual/shapes.ts.",
  aspect: "16:9",
  source: "nano-banana",
}));

export default function Creatives() {
  return (
    <div className="mx-auto max-w-6xl px-6 py-16 space-y-16">
      <header>
        <p className="text-xs uppercase tracking-[0.2em] text-clay mb-4">
          08 - Creatives review
        </p>
        <h1 className="text-5xl font-semibold tracking-tight text-ink leading-[1.05]">
          The visual{" "}
          <span className="text-sage italic font-normal">language</span>.
        </h1>
        <p className="mt-6 text-lg text-ink-soft max-w-2xl leading-relaxed">
          First samples, the recurring cast, and the abstract drill vocabulary.
          Approve, reject, leave notes per image. Decisions persist in your
          browser.
        </p>
      </header>

      <section>
        <SectionHeader
          eyebrow="A"
          title="The cast - group hero"
          body="The consistency test. All four cast members in one frame. If their faces hold here, they hold everywhere."
        />
        <CreativesReview creatives={GROUP_HEROES} />
      </section>

      <section>
        <SectionHeader
          eyebrow="B"
          title="The cast - canonical portraits"
          body="Four recurring characters with stable visual descriptors. Reused across LPs, quiz interstitials, plan reveal, and ad creative. New scenes prepend the character's description for consistency."
        />
        <CreativesReview creatives={CAST_CREATIVES} />
      </section>

      <section>
        <SectionHeader
          eyebrow="C"
          title="Maria - in-pose scenes"
          body="Test of single-character consistency in active poses. Each scene generated by prepending Maria's stable description to a scene-specific prompt. If Maria reads as Maria across these, the system works."
        />
        <CreativesReview creatives={MARIA_SCENES} />
      </section>

      <section>
        <SectionHeader
          eyebrow="D"
          title="Drill archetypes (parked)"
          body="Abstract shapes for non-character slots. Direction confirmed; specific use-cases pending Lior's feedback. Kept here for visibility."
        />
        <CreativesReview creatives={SHAPE_CREATIVES} />
      </section>

      <section>
        <SectionHeader
          eyebrow="E"
          title="First-pass samples"
          body="The original four sample images that established the look. One-offs (not in the cast). Kept for reference and tonal benchmark."
        />
        <CreativesReview creatives={SAMPLES} />
      </section>

      <section className="border-t border-line pt-10">
        <h2 className="text-lg font-semibold text-ink">How the cast scales</h2>
        <p className="mt-4 text-sm text-ink-soft leading-relaxed max-w-3xl">
          Each cast member has a stable description in{" "}
          <code className="text-xs bg-paper-warm/40 px-2 py-1 rounded">
            src/lib/visual/cast.ts
          </code>
          . When we generate a new scene (e.g., &ldquo;Eleanor doing a balance
          hold by a wooden chair&rdquo;), we prepend her description and cite
          her canonical image. This keeps her looking like Eleanor across the
          site.
        </p>
        <p className="mt-3 text-sm text-ink-soft leading-relaxed max-w-3xl">
          Drill shapes work the same way: each has a typed entry in{" "}
          <code className="text-xs bg-paper-warm/40 px-2 py-1 rounded">
            src/lib/visual/shapes.ts
          </code>{" "}
          with a meaning and a usage map, so we can call{" "}
          <code className="text-xs bg-paper-warm/40 px-2 py-1 rounded">
            shapeForGoal(&apos;posture&apos;)
          </code>{" "}
          and get the right backdrop programmatically.
        </p>
      </section>
    </div>
  );
}

function SectionHeader({
  eyebrow,
  title,
  body,
}: {
  eyebrow: string;
  title: string;
  body: string;
}) {
  return (
    <div className="mb-8 border-t border-line pt-8">
      <p className="text-xs uppercase tracking-[0.2em] text-clay mb-2">{eyebrow}</p>
      <h2 className="text-3xl font-semibold tracking-tight text-ink">{title}</h2>
      <p className="mt-3 text-ink-soft max-w-3xl leading-relaxed">{body}</p>
    </div>
  );
}
